create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_first_name text not null,
    customer_last_name text not null,
    customer_name text not null,
    phone text not null,
    delivery_address text not null,
    delivery_entrance text,
    delivery_apartment text,
    delivery_intercom text,
    delivery_floor text,
    items_count integer not null default 0,
    subtotal_amount numeric(12, 2) not null default 0,
    delivery_amount numeric(12, 2) not null default 0,
    total_amount numeric(12, 2) not null default 0,
    status text not null default 'new',
    source text not null default 'website',
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    product_id text,
    product_name text not null,
    unit_price numeric(12, 2) not null default 0,
    quantity integer not null default 1,
    line_total numeric(12, 2) not null default 0,
    image_url text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.create_order_with_items(order_payload jsonb, items_payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_order_id bigint;
begin
    insert into public.orders (
        customer_first_name,
        customer_last_name,
        customer_name,
        phone,
        delivery_address,
        delivery_entrance,
        delivery_apartment,
        delivery_intercom,
        delivery_floor,
        items_count,
        subtotal_amount,
        delivery_amount,
        total_amount,
        status,
        source,
        raw_payload
    )
    values (
        coalesce(order_payload->>'customer_first_name', ''),
        coalesce(order_payload->>'customer_last_name', ''),
        coalesce(order_payload->>'customer_name', ''),
        coalesce(order_payload->>'phone', ''),
        coalesce(order_payload->>'delivery_address', ''),
        nullif(order_payload->>'delivery_entrance', ''),
        nullif(order_payload->>'delivery_apartment', ''),
        nullif(order_payload->>'delivery_intercom', ''),
        nullif(order_payload->>'delivery_floor', ''),
        coalesce((order_payload->>'items_count')::integer, 0),
        coalesce((order_payload->>'subtotal_amount')::numeric, 0),
        coalesce((order_payload->>'delivery_amount')::numeric, 0),
        coalesce((order_payload->>'total_amount')::numeric, 0),
        coalesce(order_payload->>'status', 'new'),
        coalesce(order_payload->>'source', 'website'),
        coalesce(order_payload->'raw_payload', '{}'::jsonb)
    )
    returning id into new_order_id;

    insert into public.order_items (
        order_id,
        product_id,
        product_name,
        unit_price,
        quantity,
        line_total,
        image_url
    )
    select
        new_order_id,
        nullif(item->>'product_id', ''),
        coalesce(nullif(item->>'product_name', ''), 'Товар'),
        coalesce((item->>'unit_price')::numeric, 0),
        greatest(coalesce((item->>'quantity')::integer, 1), 1),
        coalesce((item->>'line_total')::numeric, 0),
        nullif(item->>'image_url', '')
    from jsonb_array_elements(coalesce(items_payload, '[]'::jsonb)) as item;

    return new_order_id;
end;
$$;
